### ISSUE TITLE
Demo data should be removed from the container

### ISSUE THREAD

**Issue by brianmacy** [Senzing/senzingapi-tools#10]
./python/demo/truth/truthset-project3.json
./python/demo/truth/truthset-project1.json
./python/demo/truth/truthset-project2.json
./python/demo/truth/reference.json
./python/demo/truth/watchlist.json
./python/demo/truth/customers.json
./python/demo/sample/project.json
./python/demo/sample/sample_person.json
./python/demo/sample/sample_company.json

**Comment by docktermj** [comment]
@jeffadair I see that this is done in the "Projects".  Should it be marked as "closed"?

**Comment by jeffadair** [comment]
@docktermj yes.
