### ISSUE TITLE
Integrate AWS Codepipeline and Git Action

### ISSUE THREAD

**Issue by mahchiahui** [Senzing/senzingapi-tools#29]
Similar to https://github.com/Senzing/senzingapi-runtime/issues/35

Merge request, use git actions to trigger code pipeline
- [x] build docker image
- [x] test docker image with basic test

Push to main branch, use git actions to trigger code pipeline
- [x] build docker image
- [x] conduct integration via docker-compose
- [x] push image to ECR

**Comment by docktermj** [comment]
Held final review today.  Thank you @mahchiahui !

Pull requests:

- https://github.com/Senzing/senzingapi-tools/pull/32
- https://github.com/Senzing/senzingapi-tools/pull/37
